# Generated by Django 5.2.7 on 2025-10-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0002_engineer_end_data_engineer_engineer_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='engineer_status',
            field=models.CharField(max_length=20),
        ),
    ]
