# Generated by Django 5.2.7 on 2025-10-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0003_alter_engineer_engineer_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineer',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='engineer',
            old_name='sales_name',
            new_name='sales',
        ),
    ]
