# Generated by Django 5.2.7 on 2025-11-05 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0004_rename_company_name_engineer_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='end_data',
        ),
        migrations.AddField(
            model_name='engineer',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whiteboard.company'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
