# Generated by Django 5.2.7 on 2025-11-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0005_remove_engineer_end_data_engineer_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='engineer_status',
            field=models.CharField(default='勤務中', max_length=20),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='engineer_type',
            field=models.CharField(default='正社員', max_length=50),
        ),
    ]
