# Generated by Django 5.2.7 on 2025-11-11 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0006_alter_engineer_engineer_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='engineer_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='engineer_status',
            field=models.CharField(default='勤務中', max_length=20, null=True),
        ),
    ]
