# Generated by Django 5.2.7 on 2025-11-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiteboard', '0007_alter_engineer_engineer_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='engineer_status',
            field=models.CharField(choices=[('今月入社', '今月入社'), ('来月入社', '来月入社'), ('勤務中', '勤務中'), ('今回終了', '今回終了'), ('退職予定', '退職予定')], default='勤務中', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='engineer_type',
            field=models.CharField(choices=[('正社員', '正社員'), ('私宅', '私宅'), ('新卒', '新卒'), ('グローバル', 'グローバル')], default='正社員', max_length=50),
        ),
    ]
